"""add tags to products

Revision ID: ca391fd4ecb5
Revises: e00ec28be82e
Create Date: 2026-09-27 17:10:50.652720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca391fd4ecb5'
down_revision = 'e00ec28be82e'
branch_labels = None
depends_on = None


def upgrade():
    # MySQL rejects a literal DEFAULT on JSON columns, so add it nullable,
    # backfill, then tighten to NOT NULL.
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))

    op.execute("UPDATE products SET tags = '[]' WHERE tags IS NULL")

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('tags', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
