"""add installment_plans to products

Revision ID: e00ec28be82e
Revises: e2ac7c97a89a
Create Date: 2026-09-27 16:33:08.102565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e00ec28be82e'
down_revision = 'e2ac7c97a89a'
branch_labels = None
depends_on = None


def upgrade():
    # MySQL rejects a literal DEFAULT on JSON columns, so add it nullable,
    # backfill, then tighten to NOT NULL.
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('installment_plans', sa.JSON(), nullable=True))

    op.execute("UPDATE products SET installment_plans = '[]' WHERE installment_plans IS NULL")

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('installment_plans', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('installment_plans')

    # ### end Alembic commands ###
