"""add brand and subcategory to products

Revision ID: e2ac7c97a89a
Revises: cbd6f7e3f7d6
Create Date: 2026-09-22 23:30:57.887825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ac7c97a89a'
down_revision = 'cbd6f7e3f7d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory', sa.String(length=100), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('brand', sa.String(length=100), nullable=False, server_default=''))
        batch_op.create_index(batch_op.f('ix_products_subcategory'), ['subcategory'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_subcategory'))
        batch_op.drop_column('brand')
        batch_op.drop_column('subcategory')

    # ### end Alembic commands ###
